version: '3.8'

services:

  app:
    build: .
    restart: always
    # platform: linux/amd64
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
